exclude = [
    "manage.py",
    "docs",
    "*/migrations",
]

[format]
quote-style = "double"
docstring-code-format = true
indent-style = "space"
line-ending = "lf"

[lint]
select = ["ALL"]

ignore = [
    "RUF001",  # CYRILLIC LETTER
    "ANN001",  # Missing type annotation for function argument
    "ANN002",  # Missing type annotation for `*args`
    "ANN003",  # Missing type annotation for `**kwargs`
    "ANN204",  # Missing return type annotation
    "ARG002",  # Unused method argument: `request`
    "D104",  # Missing docstring in public package
    "D105",  # Skipping docstrings in magic methods (__init__, etc.)
    "D203",  # Conflicts with D211 (one-blank-line-before-class)
    "D213",  # Conflicts with D212 (multi-line-summary-second-line)
    "COM812", # RECOMMENDED: Ignore when using ruff format to avoid conflicts
    "ISC001", # RECOMMENDED: Ignore when using ruff format
]
