# Generated by Django 5.2.10 on 2026-02-03 17:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор', primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Дата последнего изменения', verbose_name='Изменен')),
                ('number', models.PositiveBigIntegerField(editable=False, help_text='Номер обращения', verbose_name='Номер')),
                ('title', models.CharField(editable=False, max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('active', 'В работе'), ('closed', 'Закрытая'), ('archived', 'В архиве')], default='new', help_text='Текущий статус обращения', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Все заявки',
            },
        ),
        migrations.CreateModel(
            name='ActiveTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка в работе',
                'verbose_name_plural': 'В работе',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appticket.ticket',),
        ),
        migrations.CreateModel(
            name='ArchivedTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка в архиве',
                'verbose_name_plural': 'Архивные',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appticket.ticket',),
        ),
        migrations.CreateModel(
            name='ClosedTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Закрытая заявка',
                'verbose_name_plural': 'Закрытые',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appticket.ticket',),
        ),
        migrations.CreateModel(
            name='NewTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Новая заявка',
                'verbose_name_plural': 'Новые',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appticket.ticket',),
        ),
    ]
