# Generated by Django 5.2.10 on 2026-05-28 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Дата последнего изменения', verbose_name='Изменен')),
                ('number', models.PositiveBigIntegerField(editable=False, help_text='Номер обращения в системе', verbose_name='Номер')),
                ('title', models.CharField(help_text='Коротко о главном', max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('active', 'В работе'), ('paused', 'Приостановлена'), ('closed', 'Закрыта'), ('archived', 'Архивиорована')], default='new', help_text='Статус обращения', max_length=10, verbose_name='Статус')),
                ('detail', models.TextField(blank=True, help_text='Суть проблемы', verbose_name='Подробно')),
                ('executor', models.ForeignKey(blank=True, help_text='Назначить на пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Дата последнего изменения', verbose_name='Изменен')),
                ('type', models.CharField(choices=[('comment', 'Коментарий'), ('call', 'Звонок клиенту'), ('pause', 'Приостановить'), ('close', 'Закрыть')], default='comment', help_text='Выберите тип события', verbose_name='Тип события')),
                ('title', models.CharField(help_text='Коротко о главном', max_length=255, verbose_name='Заголовок')),
                ('comment', models.TextField(help_text='Прокоментируйте ваши действия.', verbose_name='Коментарий')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('ticket', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='appticket.ticket')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='ActiveTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Обращение в работе',
                'verbose_name_plural': 'Обращения в работе',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appticket.ticket',),
        ),
        migrations.CreateModel(
            name='ArchivedTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Архивное обращение',
                'verbose_name_plural': 'Архивные обращения',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appticket.ticket',),
        ),
        migrations.CreateModel(
            name='ClosedTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Закрытое обращение',
                'verbose_name_plural': 'Закрытые обращения',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appticket.ticket',),
        ),
        migrations.CreateModel(
            name='NewTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Новое обращение',
                'verbose_name_plural': 'Новые обращения',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appticket.ticket',),
        ),
    ]
