# Generated by Django 5.2.10 on 2026-06-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
