# Generated by Django 5.2.10 on 2026-06-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appticket', '0002_remove_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата создания', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Дата последнего изменения', verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата создания', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Дата последнего изменения', verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='ticketqueue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата создания', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='ticketqueue',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Дата последнего изменения', verbose_name='Изменен'),
        ),
    ]
