# Generated by Django 5.2.10 on 2026-06-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appticket', '0003_alter_event_created_alter_event_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('assigned', 'Назначено'), ('active', 'В работе'), ('paused', 'Приостановлена'), ('closed', 'Закрыта'), ('archived', 'Архивиорована')], default='new', help_text='Статус обращения', max_length=10, verbose_name='Статус'),
        ),
    ]
