# Generated by Django 5.2.10 on 2026-06-08 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appticket', '0004_alter_ticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='initiator',
            field=models.ForeignKey(blank=True, help_text='Инициатор обращения.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='init_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='executor',
            field=models.ForeignKey(blank=True, help_text='Назначить на пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execute_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
